In [3]:
import numpy as np

In [4]:
# Creating Numpy Array

In [5]:
my_list = [1,2,3]

In [6]:
x = np.array(my_list)

In [7]:
type(x)

numpy.ndarray

In [8]:
x

array([1, 2, 3])

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [15]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [16]:
type(1)

int

In [17]:
type(1.0)

float

In [18]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [19]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [20]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [21]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [22]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [23]:
np.linspace(0,10,3)

array([  0.,   5.,  10.])

In [24]:
np.linspace(0,10,30)

array([  0.        ,   0.34482759,   0.68965517,   1.03448276,
         1.37931034,   1.72413793,   2.06896552,   2.4137931 ,
         2.75862069,   3.10344828,   3.44827586,   3.79310345,
         4.13793103,   4.48275862,   4.82758621,   5.17241379,
         5.51724138,   5.86206897,   6.20689655,   6.55172414,
         6.89655172,   7.24137931,   7.5862069 ,   7.93103448,
         8.27586207,   8.62068966,   8.96551724,   9.31034483,
         9.65517241,  10.        ])

In [25]:
np.linspace(0,10,50)

array([  0.        ,   0.20408163,   0.40816327,   0.6122449 ,
         0.81632653,   1.02040816,   1.2244898 ,   1.42857143,
         1.63265306,   1.83673469,   2.04081633,   2.24489796,
         2.44897959,   2.65306122,   2.85714286,   3.06122449,
         3.26530612,   3.46938776,   3.67346939,   3.87755102,
         4.08163265,   4.28571429,   4.48979592,   4.69387755,
         4.89795918,   5.10204082,   5.30612245,   5.51020408,
         5.71428571,   5.91836735,   6.12244898,   6.32653061,
         6.53061224,   6.73469388,   6.93877551,   7.14285714,
         7.34693878,   7.55102041,   7.75510204,   7.95918367,
         8.16326531,   8.36734694,   8.57142857,   8.7755102 ,
         8.97959184,   9.18367347,   9.3877551 ,   9.59183673,
         9.79591837,  10.        ])

In [26]:
np.linspace(0,10,51)

array([  0. ,   0.2,   0.4,   0.6,   0.8,   1. ,   1.2,   1.4,   1.6,
         1.8,   2. ,   2.2,   2.4,   2.6,   2.8,   3. ,   3.2,   3.4,
         3.6,   3.8,   4. ,   4.2,   4.4,   4.6,   4.8,   5. ,   5.2,
         5.4,   5.6,   5.8,   6. ,   6.2,   6.4,   6.6,   6.8,   7. ,
         7.2,   7.4,   7.6,   7.8,   8. ,   8.2,   8.4,   8.6,   8.8,
         9. ,   9.2,   9.4,   9.6,   9.8,  10. ])

In [27]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [28]:
np.random.rand(1)

array([ 0.73498047])

In [29]:
np.random.rand(1)

array([ 0.21141811])

In [30]:
np.random.rand(1)

array([ 0.83977059])

In [32]:
np.random.rand(5,4)

array([[ 0.91724305,  0.64165719,  0.95584018,  0.50421962],
       [ 0.16529467,  0.87363603,  0.50034899,  0.25416494],
       [ 0.63040715,  0.15493775,  0.13641725,  0.87224851],
       [ 0.85638789,  0.49008059,  0.48082753,  0.17137623],
       [ 0.60832436,  0.27648749,  0.16078912,  0.01087387]])

In [33]:
np.random.randn(5)

array([-0.8008996 ,  0.05257513,  0.11662753,  1.1451323 , -0.015829  ])

In [34]:
np.random.randn(5,4)

array([[-1.05526368, -0.58646008, -0.31002961,  0.59481667],
       [-1.69847701, -0.42887907, -1.36312035,  0.31922192],
       [-0.6492632 ,  0.28504616,  1.41113136, -1.14444224],
       [-0.9661059 , -0.67978   ,  0.12156403, -0.09755364],
       [-1.25915857,  1.06557744,  0.75274732, -0.33206514]])

In [35]:
np.random.randint(1,100)

97

In [36]:
np.random.randint(1,100)

5

In [37]:
np.random.randint(1,100,10)

array([29, 29, 34, 43,  6, 70, 89, 80, 93, 11])

In [39]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr

array([48, 36,  1, 39, 47, 14, 23, 26, 40,  0])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr.shape

(25,)

In [44]:
arr.reshape(5,5).shape

(5, 5)

In [45]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.reshape(25,1).shape

(25, 1)

In [47]:
arr.dtype

dtype('int32')

In [48]:
ranarr

array([48, 36,  1, 39, 47, 14, 23, 26, 40,  0])

In [49]:
ranarr.max()

48

In [50]:
ranarr.argmax()

0

In [51]:
ranarr.min()

0

In [52]:
ranarr.argmin()

9