In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Broadcasting
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_arr = arr[0:6]

In [15]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 200

In [22]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
# mat[row, column]
# mat[row][col]

In [26]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [27]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [28]:
 mat[0]

array([ 5, 10, 15])

In [29]:
mat[2]

array([35, 40, 45])

In [30]:
mat[1][1]

25

In [31]:
mat[1,1]

25

In [32]:
mat[0,2]

15

In [33]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

In [34]:
mat[1:,0:2]

array([[20, 25],
       [35, 40]])

In [35]:
# CONDITIONAL SELECTION

In [36]:
arr = np.arange(1,11)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [39]:
bool_arr = arr > 4

In [40]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [41]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [42]:
arr[arr < 9]

array([1, 2, 3, 4, 5, 6, 7, 8])