In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3])

In [4]:
x

array([1, 2, 3])

In [5]:
type(x)

numpy.ndarray

In [6]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.arange(0,11,0)

ZeroDivisionError: division by zero

In [ ]:
np.arange(0,11,2)

In [ ]:
np.zeros(3)

In [ ]:
np.zeros((3,5))

In [ ]:
np.ones(3,3)

In [ ]:
np.ones((3,3))

In [ ]:
np.linspace(0,10,3)

In [ ]:
np.random.rand(1)

In [9]:
np.random.rand(1)



array([ 0.54537632])

In [10]:
np.random.randint(1,100,3,3)

TypeError: data type not understood

In [11]:
np.random.randint(0,100,(2,2))

array([[54, 91],
       [97, 18]])

In [12]:
arr = np.arange(0,11)

In [13]:
arr_copy = arr.copy()

In [14]:
print arr
print arr_copy

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-14-1c1922ce1881>, line 1)

In [15]:
print (arr)
print (arr_copy)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
arr_copy = *0

SyntaxError: can't use starred expression here (<ipython-input-16-f8a11ffc2089>, line 1)

In [17]:
arr_copy *=0

In [18]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
import pandas as pd
np.random.seed(101)

In [31]:
df = pd.DataFrame(np.random.randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])

In [32]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509